baseurl = "/"
languageCode = "en-us"
title = "Ticki"
theme = "lithium"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ticki"

[params]
    description = "I wish I were able to make up a catchy blog line here."

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
