baseurl = "http://ticki.github.io/"
languagecode = "en-us"
title = "Ticki's blog"
summerization = "html_firstparagraph"
paginate = 9
theme = "bleak"

DisqusShortname = "http-ticki-github-io"
disqus_identifier = "http-ticki-github-io"

[permalinks]
    post = "/blog/:slug/"
    # post = "/post/:year/:month/:day/:slug"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ticki"
[[menu.rss]]
    name = "/index.xml"
    url = "https://github.com/ticki"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
    cover = "/cover.png"
    Subtitle = "A blog about the beauty of mathematics and computer science."
    description = "This blog contains my thoughts, ideas, and humble discoveries in mathematics and computer science."

    disqus = "http-ticki-github-io"
    logo = "/logo.png"
    hideHUGOSupport = false
    github = "ticki"
    twitter = "ticki_"
