baseurl = "/"
languagecode = "en-us"
title = "Ticki"
theme = "bleak"
pygmentsuseclasses = true

contentdir =                 "content"
statictdir =                 "static"
layoutsdir =                 "layouts"
dataDir =                    "data"
defaultExtension =           "html"
defaultLayout =              "post"

DisqusShortname = "http-ticki-github-io"
disqus_identifier = "http-ticki-github-io"

[permalinks]
    page = "blog/:filename/"
    post = "blog/:filename/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ticki"
[[menu.rss]]
    name = "/index.xml"
    url = "https://github.com/ticki"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
    disqus = "http-ticki-github-io"
    description = "Howdy, this is my blog!"
    logo = "/logo.png"
    hideHUGOSupport = false
    githubName = "ticki"
